### ISSUE TITLE
Nightly build doxygen documentation not updated

### ISSUE THREAD

**Issue by rolanddenis** [DGtal-team/DGtal#1267] opened 2017-06-19 11:22 UTC
The nightly build of the documentation was lastly generated at November 7th (see http://dgtal.org/doc/nightly/index.html ).

**Comment by dcoeurjo** [comment] 2017-06-19 11:25
;)
I use rsync to push the doc and it transfers file only when they have changed..

**Comment by dcoeurjo** [comment] 2017-06-19 14:40
Agree... the issue is indeed important

**Comment by rolanddenis** [comment] 2017-06-20 13:44
What's up doc ? :popcorn:

**Comment by dcoeurjo** [comment] 2017-06-20 13:53
;)
There is a problem with the ssh key I use to push the doc the the liris server without asking a password...

**Comment by dcoeurjo** [comment] 2017-06-20 13:54
Still W.I.P

**Comment by rolanddenis** [comment] 2017-06-20 14:10
I see... good luck !

**Comment by rolanddenis** [comment] 2017-06-20 15:12
But is it not the same key as the one used for the release documentation ?

**Comment by dcoeurjo** [comment] 2017-06-20 15:41
The key is the same but within Travis, the process is slighlty different (keys must be encrypted) and I need to double check the config

**Comment by dcoeurjo** [comment] 2017-06-21 13:58
looks like it's fine now ;)

**Comment by dcoeurjo** [comment] 2017-06-21 13:58
closing this issue

**Closed by dcoeurjo** 2017-06-21 13:58 UTC
Labels: Documentation

**Comment by rolanddenis** [comment] 2017-06-21 19:13
Nice, thanks !
