### ISSUE TITLE
compilation on debian gcc 4.7.2

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1200] opened 2016-08-06 07:09 UTC
A new error appears on Debian GNU/Linux 7 (wheezy)
g++ (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskySpaceND<3u, int>::NEG'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskyPreSpaceND<2u, int>::NEG'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskySpaceND<3u, int>::POS'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskySpaceND<2u, int>::POS'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskySpaceND<2u, int>::NEG'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskyPreSpaceND<3u, int>::NEG'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskyPreSpaceND<3u, int>::POS'
/home/kerautre/DGtal/build/src/libDGtal.so: undefined reference to `DGtal::KhalimskyPreSpaceND<2u, int>::POS'

**Comment by kerautret** [comment] 2016-08-06 08:54
Confirmed after upgrade to Jessie no more this errors...

**Comment by rolanddenis** [comment] 2016-08-06 13:53
While compiling DGtal library (default options ?) or an another program ?

**Comment by kerautret** [comment] 2016-08-06 14:37
yes it was compilling DGtal examples

**Comment by rolanddenis** [comment] 2016-08-06 16:18
Which one ? Any details ?
It could be a compiler bug but it is true that no reference can be taken to those static members if the class is not explicitly defined. I have tested with 4.7.4 (under Ubuntu 15.10) and examples compile successfully but not `testKhalimskySpaceND` (another error) :confused:

**Comment by kerautret** [comment] 2016-08-06 16:43
The compilation was not given other details than that,  it was on examples/tools using KhalimskySpaceND (using board if I remember), the tools also failed and many other perso tools using DGtal...  It was working near febrary because I compiled other demo. I will look if some ipol server have also this version ...

**Comment by rolanddenis** [comment] 2016-08-06 21:48
Ok, I have reproduced the issue on a fresh install of Debian Wheezy. It appends for every file that links to `libDGtal.so` because `Khalimsky(Pre)SpaceND` is explicitly instantiated in `StdDefs.cpp` which is included in the library.
I don't know why the compiler complains about taking references to those static members since there is no need of that in DGtal source (and other compiler versions are OK with that) ... but it is easily fixable by providing a definition of those members in the namespace scope (like in the corresponding `.ih` file), as in this answer : http://stackoverflow.com/questions/16467802/undefined-reference-with-g4-7-3-and-g4-8?answertab=votes#tab-top

Actually, it worked in February because there were such definitions in namespace scope in the `.ih` (if the system was not Windows ...) but I removed it since I thought it was not necessary anymore ... my bad :sweat: 

I will soon push a fix for this issue !

**Comment by kerautret** [comment] 2016-08-07 15:58
ok thank for the feed back, difficult to test all config with travis ;)

**Comment by rolanddenis** [comment] 2016-08-22 16:06
Fixed.

**Closed by rolanddenis** 2016-08-22 16:06 UTC
Labels: Build, Topology
