### ISSUE TITLE
Example compilation issue with template spec

### ISSUE THREAD

**Issue by kerautret** [DGtal-team/DGtal#1474] opened 2020-04-09 08:33 UTC
Probably from the 10.15.4 update with last Xcode I get this error:

In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__string:56:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2567:5: error: 
      static_assert failed due to requirement
      '__is_forward_iterator<DGtal::ConstIteratorAdapter<DGtal::HyperRectDomain_Iterator<DGtal::PointVector<2,
      int, std::__1::array<int, 2> > >, DGtal::DistanceTransformation<DGtal::SpaceND<2, int>,
      DGtal::functors::SimpleThresholdForegroundPredicate<DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<2,
      int> >, unsigned int> >, DGtal::ExactPredicateLpSeparableMetric<DGtal::SpaceND<2, int>, 2, long
      long>, DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<2, int> >,
      DGtal::PointVector<2, int, std::__1::array<int, 2> > > >, double> >::value' "std::max_element
      requires a ForwardIterator"
    static_assert(__is_forward_iterator<_ForwardIterator>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:2586:19: note: 
      in instantiation of function template specialization
      'std::__1::max_element<DGtal::ConstIteratorAdapter<DGtal::HyperRectDomain_Iterator<DGtal::PointVector<2,
      int, std::__1::array<int, 2> > >, DGtal::DistanceTransformation<DGtal::SpaceND<2, int>,
      DGtal::functors::SimpleThresholdForegroundPredicate<DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<2,
      int> >, unsigned int> >, DGtal::ExactPredicateLpSeparableMetric<DGtal::SpaceND<2, int>, 2, long
      long>, DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<2, int> >,
      DGtal::PointVector<2, int, std::__1::array<int, 2> > > >, double>, std::__1::__less<double, double>
      >' requested here
    return _VSTD::max_element(__first, __last,
                  ^
DGtal/examples/geometry/volumes/distance/toricdomainvolumetric.cpp:119:49: note: 
      in instantiation of function template specialization
      'std::__1::max_element<DGtal::ConstIteratorAdapter<DGtal::HyperRectDomain_Iterator<DGtal::PointVector<2,
      int, std::__1::array<int, 2> > >, DGtal::DistanceTransformation<DGtal::SpaceND<2, int>,
      DGtal::functors::SimpleThresholdForegroundPredicate<DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<2,
      int> >, unsigned int> >, DGtal::ExactPredicateLpSeparableMetric<DGtal::SpaceND<2, int>, 2, long
      long>, DGtal::ImageContainerBySTLVector<DGtal::HyperRectDomain<DGtal::SpaceND<2, int> >,
      DGtal::PointVector<2, int, std::__1::array<int, 2> > > >, double> >' requested here
  const DTL2::Value       maxv2       = * (std::max_element(dtL2.constRange().begin(), dtL2.const...
                                                ^
1 error generated.

**Comment by rolanddenis** [comment] 2020-04-09 10:26
Is that not a duplicate of #1437 ? (the `__is_forward_iterator` requirement that fails)

**Comment by rolanddenis** [comment] 2020-04-09 10:57
Yes it is, same file, same line. Closing...

**Closed by rolanddenis** 2020-04-09 10:57 UTC

**Comment by kerautret** [comment] 2020-04-09 12:34
> Yes it is, same file, same line. Closing...

Sorry @rolanddenis I miss it.
