### ISSUE TITLE
BOOST_DEFINE_MATH_CONSTANT errors

### ISSUE THREAD

**Issue by BorisMansencal** [DGtal-team/DGtal#1298] opened 2017-12-06 15:20 UTC
I am trying to build a simple program using DGtal (current git head) and ITK (4.12.2), but not Boost : 

```
#include "DGtal/base/Common.h"
#include "DGtal/io/readers/GenericReader.h"
#include "DGtal/images/ImageContainerByITKImage.h"

int
main(int argc, char *argv[])
{
  if (argc != 2) {
    std::cerr<<"Usage: "<<argv[0]<<" imageFilename\n";
    exit(10);
  }

  const std::string filename = argv[1];

  typedef DGtal::Z3i::Domain Domain;
  typedef DGtal::ImageContainerByITKImage<Domain, int> Image;

  typename Image::ITKImagePointer p = DGtal::ITKReader<Image>::importITK(filename).getITKImagePointer();

  std::cout<<"dim="<<p->ImageDimension<<"\n";
  
  return 0;
}

```

With git versions till 5f6c8b8dbffa27c7b12151f7590295377507294d, it compiles correctly.
From commit 18b1a67c04ba1b7c83953ae27dae4721b0361491 onwards, I get a lot of errors:

```

In file included from /usr/include/boost/config.hpp:61:0,
                 from /usr/include/boost/concept/assert.hpp:7,
                 from /usr/include/boost/concept_check.hpp:20,
                 from /tools/DGtal_git/src/DGtal/base/Common.h:55,
                 from /test0/testDEBUG.cpp:2:
/usr/include/boost/math/constants/constants.hpp: In static member function ‘static constexpr T boost::math::constants::detail::constant_half<T>::get(const mpl_::int_<5>&)’:
/usr/include/boost/math/constants/constants.hpp:277:3: error: unable to find numeric literal operator ‘operator""Q’
   BOOST_DEFINE_MATH_CONSTANT(half, 5.000000000000000000000000000000000000e-01, "5.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000e-01")
   ^
/usr/include/boost/math/constants/constants.hpp:277:3: note: use -std=gnu++11 or -fext-numeric-literals to enable more built-in suffixes
/usr/include/boost/math/constants/constants.hpp: In static member function ‘static constexpr T boost::math::constants::detail::constant_third<T>::get(const mpl_::int_<5>&)’:
/usr/include/boost/math/constants/constants.hpp:278:3: error: unable to find numeric literal operator ‘operator""Q’
   BOOST_DEFINE_MATH_CONSTANT(third, 3.333333333333333333333333333333333333e-01, "3.33333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333e-01")
   ^

```
[...]

I am on Ubuntu 16.04 (gcc 5.4.0). 
Do I have to use boost ?

**Comment by copyme** [comment] 2017-12-07 09:03
Hello @BorisMansencal! I had a similar problem on the previous stable version of openSUSE i.e., 43.1 and gcc 4.8.5. I did not have time to figure this out but the point is that clang could compile the code so I simply switched from gcc to clang. Maybe try this way.

**Comment by dcoeurjo** [comment] 2017-12-07 11:28
In addition to @copyme ‘s comment, yes Boost is required to build DGtal.

**Comment by BorisMansencal** [comment] 2017-12-07 15:13
To build DGtal, yes. But to build a program depending on DGtal ?
Till 20 days ago, my program compiled just fine.

**Comment by dcoeurjo** [comment] 2017-12-07 15:20
To build an external program, yes boost is also required (DGtal is a very small built lib and a bunch of header files that are compiled during the build of your external program).

20days ago, maybe the boost location was on a canonical folder and your compiler found it automatically. 
Since the very first release, Boost is mandatory. Something may have changed on your system

**Comment by dcoeurjo** [comment] 2017-12-07 15:20
BTW, are you compiling your external lib with the C++11 flags ?

**Comment by BorisMansencal** [comment] 2017-12-07 16:21
What I meant was that with the DGtal git head of 20 days ago 5f6c8b8 my program compiles just fine. But since 18b1a67 it seems to require Boost.
Yes, I am compiling in c++11.

I have made some progress.
With current git head:
- with gcc 5.4.0,
  - with -std=c++11, it does not compile (see errors in initial post)
  -  with -std=gnu++11 it  compiles just fine. However, if both -std=c++11 and -std=gnu++11 are specified, it does not compile.
  - with -std=c++11 and -fext-numeric-literals, it compiles just fine.

- with clang 5.0 
  - with -std=c++11 my program compiles just fine (with some warnings on some boost_concept_checks)
  - with -std=gnu++11 my program compiles just fine (with some warnings on some boost_concept_checks)
  - with -std=c++11 and -fext-numeric-literals, it does not compile as -fext-numeric-literals is not a recognized option.

**Comment by copyme** [comment] 2017-12-07 16:26
@BorisMansencal as @dcoeurjo said boost was required since I can remember. From your last message it looks like the problem which I had with gcc on openSUSE 43.1.

**Comment by copyme** [comment] 2017-12-07 16:46
Anyway, I think the problem is with Boost and it has nothing to do with DGtal.

**Comment by dcoeurjo** [comment] 2017-12-08 09:17
(another question: do the examples / tests compile ?)

**Comment by copyme** [comment] 2017-12-08 10:18
@dcoeurjo In my case they did not. But it was some months ago, and not like @BorisMansencal said weeks/days. Maybe some updates for Ubuntu brought the problem in. Hard to say.

**Comment by BorisMansencal** [comment] 2017-12-08 12:12
Sorry, I was not clear in my previous message. It is not "since 18b1a67 it seems to require Boost.". It always has. It is "since 18b1a67 it seems to require a specific option (-std=gnu++11 or -fext-numeric-literals) to compile". But may be, this option was already necessary and my toy program was just an exception ?

Both DGtal examples and tests compile fine. I see that tests use "-std=gnu++11" (so it is expected that they compile fine). 

I have also tested on Fedora 27 (with gcc 7.2.1 and Boost 1.64). My toy program compiles find with only -std=c++11.

**Comment by dcoeurjo** [comment] 2017-12-08 12:38
Okay.. what I see is this PR #1290, we have fixed a c++11 flags issue (we now let cmake set the flags).

Could you share with us (using gist for instance) the CMakeLists.txt file of your toy example ?

If examples, tests, and dgtaltools are fine, the problem does not seem to come from us.

**Comment by BorisMansencal** [comment] 2017-12-08 13:20
Here is my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.0)

PROJECT(test)

FIND_PACKAGE(DGtal REQUIRED)

IF(WITH_ITK)
  ADD_EXECUTABLE(testDEBUG testDEBUG.cpp )
  TARGET_INCLUDE_DIRECTORIES(testDEBUG PUBLIC "${DGTAL_INCLUDE_DIRS}")
  TARGET_COMPILE_OPTIONS(testDEBUG PUBLIC -Wall -std=c++11)
  TARGET_LINK_LIBRARIES(testDEBUG ${DGTAL_LIBRARIES})
ENDIF(WITH_ITK)

```
I have indeed the same issues that @phcerdan referenced in PR #1290 
If I remove the "-std=c++11" from my CMakeLists.txt, the code compiles fine (because DGTal brings "-std=gnu++11").

Ok, so the solution seems to be to avoid to use "-std=c++11" explicitly with DGtal (because when both "-std=c++11" and "-std=gnu++11" are specified, the second is ignored).

**Comment by dcoeurjo** [comment] 2017-12-08 13:27
The issue must be elsewhere because c++11 is mandatory in DGtal.

**Comment by dcoeurjo** [comment] 2017-12-08 13:28
The ```find_package```  set all flags for you (and if you look at DGtalConfig.cmake generated by DGtal, you'd see the c++11 stuff)

**Comment by dcoeurjo** [comment] 2017-12-08 13:29
okay I see your "-std=c++11" and "-std=gnu++11"

**Comment by dcoeurjo** [comment] 2017-12-08 13:31
If you look a the links in the issue that #1290 fixes, you can see that it is not a good idea to set the ```std``` flag manually. Cmake does the job using ```set(CMAKE_CXX_STANDARD 11)```.

Otherwise there might be side effects and your problem may come from that

**Comment by JacquesOlivierLachaud** [comment] 2018-01-27 14:12
Just a comment. This error on BOOST_MATH_CONSTANT is related to a known bug in gcc 4-8.
See https://svn.boost.org/trac10/ticket/9240

**Comment by dcoeurjo** [comment] 2018-02-24 19:44
@BorisMansencal can I close this issue?

**Comment by BorisMansencal** [comment] 2018-02-26 08:46
Yes you can close this issue.
If it will

**Comment by dcoeurjo** [comment] 2018-02-26 08:47
thx

**Closed by dcoeurjo** 2018-02-26 08:47 UTC
