### ISSUE TITLE
Problem in testRigidTransform2D

### ISSUE THREAD

**Issue by JacquesOlivierLachaud** [DGtal-team/DGtal#1033] opened 2015-07-21 11:16 UTC
The test testRigidTransform2D sometimes loops indefinitely. This seems related to bad image width when exporting to PGM. Because of that, the exported image fills the harddisk. Apparently, there are bad computations of new bounds of transformed image. I suspect a sign problem when converting integers to double and reciprocally in class DomainRigidTransformation2D. For now, the test testRigidTransform2D has been suspended in PR #1032

**Comment by dcoeurjo** [comment] 2015-09-01 07:33
@copyme could you please have a look to this issue before the 0.9 release ? 
thanks

**Comment by copyme** [comment] 2015-09-01 13:15
@dcoeurjo Yes, I will take a look as soon as possible.

**Comment by copyme** [comment] 2015-09-01 17:07
I took a look and everything seems to be fine. I've ran this code many times and no problem at all. @JacquesOlivierLachaud Do you have any additional information which could help to debug? The problem has occurred on Linux or Mac?

**Comment by dcoeurjo** [comment] 2015-09-02 07:00
The issue is difficult to reproduce (everything is fine on Travis --ubuntu-- and my computer --mac--) but I have students who also reported me a memory issue (huge malloc) in the rotation code. 
I've no backtrace but I suspect an (numerical) issue in the output domain computation...

**Comment by dcoeurjo** [comment] 2015-09-02 07:00
maybe @JacquesOlivierLachaud can have a backtrace on his computer...

**Comment by JacquesOlivierLachaud** [comment] 2015-09-02 07:17
When I ran the test (2D), it was building a huge PGM file. The header of the PGM file was indicated a width and height of more than 4 billion, which corresponds to unsigned/sign errors for computing the output domain of the rotation. The error was in the exportPGM function, but probably it was the domain handed to the exportPGM which was bad. So I suspect implicit conversion problems (double -> integer ...) when you compute the output domain for your rigid transform.

**Comment by copyme** [comment] 2015-09-02 07:45
Ok I will search for a bug. So far I have added fetestexcept ( FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW | FE_UNDERFLOW ); to testRigidTransfromation2D.cpp and no problem.

**Comment by rolanddenis** [comment] 2015-09-02 08:23
On my side, I got this bug on archlinux when using g++ 5.2.0 (with previous 5.* versions also) in Release mode only. It ran well in Debug mode and with clang 3.6.2 (both in Release and Debug mode). 
It can also be a problem with a non-initialized member in a constructor : gcc used to initialize members to 0x0 by default in Debug mode but it can take any value in Release mode.

**Comment by rolanddenis** [comment] 2015-09-02 08:45
Ok, it is a temporary lifetime problem:
in ```testRigidTransformation2D.cpp```, line 106 and 115, the domain given to ConstImageAdapter is a temporary whose lifetime ended on the same line. But the ConstImageAdapter stores a pointer to it ... this pointer is then invalid when the adapter is export in PGM on the next line.
Defining the domain in a dummy variable on the previous line and giving it to ConstImageAdapter constructor solves the problem (in my case).

But which compiler is wrong ? I think that clang sees that ConstImageAdapter constructor used a const-ref on the domain and thus extends temporary lifetime to the adapter's lifetime. g++ mayby looks further and sees that only a pointer to the domain is stored in the adapter and it is not a valid case to lifetime extension.

**Comment by rolanddenis** [comment] 2015-09-02 09:09
The §12.2/5 in C++ reference (cited by many stackoverflow answers on this topic) says that "A temporary bound to a reference member in a constructor’s ctor-initializer (12.6.2) persists until the constructor exits". So there is no reason why clang extends temporary lifetime (mayby he don't and the memory is not overwritten).

**Comment by copyme** [comment] 2015-09-02 09:14
@rolanddenis You are right. This is the source of the problem. I should notice this before. Thanks also for digging how C++ treats these cases.

**Comment by dcoeurjo** [comment] 2015-09-02 09:18
Yeah, thanks a lot @JacquesOlivierLachaud @rolanddenis & @copyme... 
I've learneed something :smile:

**Comment by dcoeurjo** [comment] 2015-09-02 10:30
Fixed in #1038 , thx

**Closed by dcoeurjo** 2015-09-02 10:30 UTC
Labels: Image
