### ISSUE TITLE
Eigen issue

### ISSUE THREAD

**Issue by skn123** [DGtal-team/DGtal#1370] opened 2018-12-01 05:55 UTC
In file included from /home/naths/srcs/DGtal/src/DGtal/math/linalg/EigenSupport.h:67:
/usr/local/include/eigen3/Eigen/SparseCholesky:34:2: error: The SparseCholesky
      module has nothing to offer in MPL2 only mode
#error The SparseCholesky module has nothing to offer in MPL2 only mode
 ^
In file included from /home/naths/srcs/DGtal/examples/dec/examplePropagation.cpp:11:
In file included from /home/naths/srcs/DGtal/src/DGtal/math/linalg/EigenSupport.h:67:
In file included from /usr/local/include/eigen3/Eigen/SparseCholesky:37:
/usr/local/include/eigen3/Eigen/src/SparseCholesky/SimplicialCholesky.h:266:72: error: 
      no template named 'AMDOrdering'; did you mean 'COLAMDOrdering'?
  ..._MatrixType, int _UpLo = Lower, typename _Ordering = AMDOrdering<typenam...
                                                          ^

**Comment by dcoeurjo** [comment] 2018-12-01 09:00
Thx for the report. Can you please send us more information on your system ?
(Eigen version, compiler...)

**Comment by skn123** [comment] 2018-12-03 05:15
UBuntu 18.04.1
CLang 6.0.0

Here is what dgtal reports during CMake.
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- -------------------------------------------------------------------------------
-- DGtal Version 1.0.beta
-- -------------------------------------------------------------------------------
-- Source DIR is /home/naths/srcs/DGtal
-- Binary/Build DIR is /home/naths/build/dgtal
-- Build type is Release
-- Installation prefix directory is /usr/local
-- Host system is Linux-4.15.0-29-generic with processor x86_64
-- Target system is Linux-4.15.0-29-generic with processor x86_64
-- -------------------------------------------------------------------------------
-- Checking if doxygen/dot is installed:
--  
-- dot found: /usr/bin/dot. Installing doc in /usr/local/share/DGtal
-- configured /home/naths/srcs/DGtal/doc/doxy.config.in --> /home/naths/build/dgtal/doxy.config
-- configured /home/naths/srcs/DGtal/doc/doxy.config.Board.in --> /home/naths/build/dgtal/doxy.config.Board
-- configured /home/naths/srcs/DGtal/doc/doxy.config.dox.in --> /home/naths/build/dgtal/doxy.config.dox
-- Clang compiler detected
-- -------------------------------------------------------------------------------
-- DGtal required dependencies: 
-- Boost version: 1.68.0
-- Checking C++11 compatibility:
--   CPP11 enabled compiler by default.
-- OK.
-- -------------------------------------------------------------------------------
-- DGtal Library optional configuration:
--    (to change these values, use ccmake, a graphical
--    cmake frontend, or define cmake commandline variables
--    -e.g. '-DWITH_GMP:string=true'-, cf documentation)
-- 
-- Removing -frounding-math flag when compiling with Clang
--  
--       WITH_OPENMP        true    (OpenMP multithread features)
--       WITH_GMP           true    (Gnu Multiprecision Library)
--       WITH_EIGEN         true    (Eigen3)
--       WITH_CGAL          false   (cgal)
--       WITH_PATATE        false   (Patate geometry library)
--       WITH_ITK           true    (Insight Toolkit ITK image wrapper)
--       WITH_CAIRO         true    (CairoGraphics drawing features)
--       WITH_HDF5          false   (HDF5 image i/o)
--       WITH_MAGICK        true    (GraphicsMagick based 2D image i/o)
--       WITH_QGLVIEWER     false   (QGLViewer based 3D Viewer -- Qt4 by default)
--       WITH_QT5           true    (Using of Qt5 instead of Qt4)
--       WITH_FFTW3         false   (FFTW3 discrete Fourier transform library)
-- 
-- For Developpers:
--       WITH_BENCHMARK     false   (Google Benchmark)
-- 
-- Checking the dependencies: 
-- GMP and GMPXX found.
--    * GMPXX has iostream capabilities
-- GraphicsMagick++ found.
-- ITK found /usr/local/lib/cmake/ITK-5.0/UseITK.cmake.
-- ITK accepts [c++11]
-- cairo found
-- OpenMP found. Libs: /usr/lib/x86_64-linux-gnu/libomp.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- Eigen3 (version 3.3.90) found.
-- -------------------------------------------------------------------------------
-- Build test files DISABLED (you can activate unit tests with '-DBUILD_TESTING=ON' cmake option)
-- -------------------------------------------------------------------------------
-- Build examples ENABLED
-- -----------------------------------------------------------------------------

**Comment by dcoeurjo** [comment] 2019-01-05 16:20
it looks like you are using Eigen 3.3.9 which is not a stable release. Could you please test again the build with Eigen 3.3.7 (latest stable) ?

**Comment by phcerdan** [comment] 2019-01-05 16:47
This could be a problem from ITK, ITK now ships an internal version of Eigen, with the option EIGEN3_MPL_ONLY.

It should not collide with any other Eigen, so It might be a bug there. I contributed to that patch in ITK, so I will be happy to narrow this down.

What version of ITK are you using? In ITK, are you using `ITK_USE_SYSTEM_EIGEN3:BOOL=ON`? 
Does this error disappear in DGtal with `WITH_ITK:BOOL=OFF`?

**Comment by phcerdan** [comment] 2019-01-05 20:38
I can reproduce this issue, I submitted a patch to ITK. Thanks for the report.

**Comment by dcoeurjo** [comment] 2019-01-06 09:03
Fantastic! Thx

**Comment by phcerdan** [comment] 2019-01-24 21:48
Fixed via https://github.com/InsightSoftwareConsortium/ITK/pull/413

**Comment by dcoeurjo** [comment] 2019-01-27 17:39
thx  @phcerdan !
@skn123 can you please update your ITK and tell us if the issue is still valid?

**Comment by dcoeurjo** [comment] 2019-08-20 15:20
is this issue still up to date ?

**Comment by phcerdan** [comment] 2019-08-20 21:08
I don't think so. It was solved in ITK.

**Closed** 2019-11-05 18:28 UTC
Labels: Base
